from . import sale_order
from . import crm_team
from . import fleet_vehicle
from . import product_template
from . import sale_order_line
from . import account_move
from . import sign_template
from . import res_partner
from . import res_config_settings
from . import sale_report
